#define TAT_DIRECTION_POINTS 20

#define TAT_FOUNDATION_SETTLED "settled"
// Wanderer foundation removed: retain the old token as an alias so legacy TAT
// slots import cleanly into the single Starter archetype.
#define TAT_FOUNDATION_WANDERER TAT_FOUNDATION_SETTLED

#define TAT_ROLE_CHOICE_STARTER "starter"
// All four legacy role choices are retained as aliases so old saves still
// denormalize safely, but gameplay now uses TAT_ROLE_CHOICE_STARTER only.
#define TAT_ROLE_CHOICE_TOWNER    TAT_ROLE_CHOICE_STARTER
#define TAT_ROLE_CHOICE_TRADER    TAT_ROLE_CHOICE_STARTER
#define TAT_ROLE_CHOICE_ADVENTURER TAT_ROLE_CHOICE_STARTER
#define TAT_ROLE_CHOICE_WRETCH    TAT_ROLE_CHOICE_STARTER

#define TAT_DIRECTION_COMBAT "combat"
#define TAT_DIRECTION_RANGED "ranged"
#define TAT_DIRECTION_MAGIC "magic"
#define TAT_DIRECTION_MIRACLES "miracles"
#define TAT_DIRECTION_MUSIC "music"
#define TAT_DIRECTION_SKILLS "skills"
#define TAT_DIRECTION_DEFENSE "defense"
#define TAT_DIRECTION_SURVIVAL "survival"
#define TAT_DIRECTION_ORDINARY "ordinary"

#define TAT_DIRECTION_ORDER list( \
	TAT_DIRECTION_COMBAT, \
	TAT_DIRECTION_RANGED, \
	TAT_DIRECTION_MAGIC, \
	TAT_DIRECTION_MIRACLES, \
	TAT_DIRECTION_MUSIC, \
	TAT_DIRECTION_SKILLS, \
	TAT_DIRECTION_SURVIVAL \
)

#define TAT_DIRECTION_NAMES list( \
	TAT_DIRECTION_COMBAT = "Melee", \
	TAT_DIRECTION_RANGED = "Ranged", \
	TAT_DIRECTION_MAGIC = "Magic", \
	TAT_DIRECTION_MIRACLES = "Miracles", \
	TAT_DIRECTION_MUSIC = "Music", \
	TAT_DIRECTION_SKILLS = "Skills", \
	TAT_DIRECTION_SURVIVAL = "Survival", \
	TAT_DIRECTION_ORDINARY = "Ordinary" \
)

// Towner battle grouping removed: single archetype uses uniform linear costs.
#define TAT_TOWNER_BATTLE_DIRECTIONS list()

#define TAT_FOUNDATION_NAMES list( \
	TAT_FOUNDATION_SETTLED = "Starter" \
)

#define TAT_FOUNDATION_ROLE_CHOICES list( \
	TAT_FOUNDATION_SETTLED = list(TAT_ROLE_CHOICE_STARTER) \
)

#define TAT_ROLE_CHOICE_NAMES list( \
	TAT_ROLE_CHOICE_STARTER = "Starter", \
	TAT_ROLE_CHOICE_TOWNER = "Starter", \
	TAT_ROLE_CHOICE_TRADER = "Starter", \
	TAT_ROLE_CHOICE_ADVENTURER = "Starter", \
	TAT_ROLE_CHOICE_WRETCH = null \
)

#define TAT_ROLE_CHOICE_EFFECTIVE_TRAITS list( \
	TAT_ROLE_CHOICE_STARTER = null, \
	TAT_ROLE_CHOICE_TOWNER = null, \
	TAT_ROLE_CHOICE_TRADER = null, \
	TAT_ROLE_CHOICE_ADVENTURER = null, \
	TAT_ROLE_CHOICE_WRETCH = null \
)

#define TAT_DIRECTION_ENTRY(_direction, _reqs, _tier) list("direction" = (_direction), "requirements" = (_reqs), "tier" = (_tier))

// Per-trait direction categorization and point requirements. Role/foundation
// GATING was removed for the single-Starter build (nobody needs to be a
// specific archetype to buy a trait), but this table is what tells the UI
// which direction tab a trait lives under and how many direction points it
// costs to unlock — that part was never meant to go away. It previously read
// as an empty list here, which silently dumped every trait into "Ordinary."
// Point thresholds below are carried over unscaled from when
// TAT_DIRECTION_POINTS was 8; now that the pool is 20, consider whether they
// should be raised to keep the same relative difficulty.
#define TAT_DIRECTION_TRAIT_RULES list( \
	TAT_TRAIT_WEAPON_TRAINING = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 1), 1), \
	TAT_TRAIT_WARRIOR_EXPERT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 3), 3), \
	TAT_TRAIT_WARRIOR_MASTER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 4), 4), \
	TAT_TRAIT_SOUNDBREAKER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MUSIC, list(TAT_DIRECTION_MUSIC = 2), 2), \
	TAT_TRAIT_RONIN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 2), 2), \
	TAT_TRAIT_SPELLBLADE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MAGIC, list(TAT_DIRECTION_MAGIC = 2), 2), \
	TAT_TRAIT_SPELLFIST = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MAGIC, list(TAT_DIRECTION_MAGIC = 2), 2), \
	TAT_TRAIT_EXPERT_ARMAMENT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MAGIC, list(TAT_DIRECTION_MAGIC = 2), 2), \
	TAT_TRAIT_WITCH_INITIATE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_BARDIC_INSPIRATION_T1 = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MUSIC, list(TAT_DIRECTION_MUSIC = 1), 1), \
	TAT_TRAIT_BARDIC_INSPIRATION_T2 = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MUSIC, list(TAT_DIRECTION_MUSIC = 3), 3), \
	TAT_TRAIT_BONUS_STAT_POOL = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 2), 2), \
	TRAIT_ARCYNE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MAGIC, list(TAT_DIRECTION_MAGIC = 1), 1), \
	TAT_TRAIT_MAGE_INITIATE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MAGIC, list(TAT_DIRECTION_MAGIC = 1), 1), \
	TAT_TRAIT_MAGE_MINOR_SLOT_1 = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MAGIC, list(TAT_DIRECTION_MAGIC = 3), 3), \
	TAT_TRAIT_MAGE_MINOR_SLOT_2 = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MAGIC, list(TAT_DIRECTION_MAGIC = 4), 4), \
	TAT_TRAIT_MAGE_MAJOR_SLOT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MAGIC, list(TAT_DIRECTION_MAGIC = 4), 4), \
	TAT_TRAIT_MAGE_UTILITY_SLOT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MAGIC, list(TAT_DIRECTION_MAGIC = 3), 3), \
	TAT_TRAIT_DIVINE_INITIATE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MIRACLES, list(TAT_DIRECTION_MIRACLES = 1), 1), \
	TAT_TRAIT_DIVINE_BOON_1 = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MIRACLES, list(TAT_DIRECTION_MIRACLES = 2), 2), \
	TAT_TRAIT_DIVINE_BOON_2 = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MIRACLES, list(TAT_DIRECTION_MIRACLES = 3), 3), \
	TAT_TRAIT_DIVINE_BOON_3 = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MIRACLES, list(TAT_DIRECTION_MIRACLES = 4), 4), \
	TAT_TRAIT_DIVINE_BLAST = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MIRACLES, list(TAT_DIRECTION_MIRACLES = 4), 4), \
	TAT_TRAIT_HERETIC = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MIRACLES, list(TAT_DIRECTION_MIRACLES = 0), 1), \
	TRAIT_RITUALIST = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MIRACLES, list(TAT_DIRECTION_MIRACLES = 3), 3), \
	TAT_TRAIT_DRUID_INITIATE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_MIRACLES, list(TAT_DIRECTION_MIRACLES = 4), 4), \
	TRAIT_DODGEEXPERT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 2), 2), \
	TRAIT_PARRYEXPERT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 2), 2), \
	TRAIT_FENCERDEXTERITY = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 1), 1), \
	TRAIT_MEDIUMARMOR = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 2), 2), \
	TRAIT_HEAVYARMOR = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 3), 3), \
	TRAIT_NOPAINSTUN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 2), 2), \
	TRAIT_CRITICAL_RESISTANCE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 3), 3), \
	TRAIT_HARDDISMEMBER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 2), 2), \
	TRAIT_STEELHEARTED = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 1), 1), \
	TRAIT_OUTDOORSMAN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 2), 2), \
	TRAIT_CIVILIZEDBARBARIAN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 2), 2), \
	TAT_TRAIT_SAVAGE_SKIN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 2), 2), \
	TAT_TRAIT_BODYBUILDER_SKIN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 2), 2), \
	TAT_TRAIT_SAVAGE_RAGE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 2), 2), \
	TAT_TRAIT_BERSERKER_RAGE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 3), 3), \
	TAT_TRAIT_TROPHY_BOUNTY = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 1), 1), \
	TAT_TRAIT_RANGED_SUPPLIER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_RANGED, list(TAT_DIRECTION_RANGED = 1), 1), \
	TAT_TRAIT_RANGED_SYNERGY_BOWS = TAT_DIRECTION_ENTRY(TAT_DIRECTION_RANGED, list(TAT_DIRECTION_RANGED = 1), 1), \
	TAT_TRAIT_RANGED_SYNERGY_CROSSBOWS = TAT_DIRECTION_ENTRY(TAT_DIRECTION_RANGED, list(TAT_DIRECTION_RANGED = 1), 1), \
	TAT_TRAIT_RANGED_SYNERGY_SLINGS = TAT_DIRECTION_ENTRY(TAT_DIRECTION_RANGED, list(TAT_DIRECTION_RANGED = 1), 1), \
	TAT_TRAIT_RANGED_SYNERGY_FIREARMS = TAT_DIRECTION_ENTRY(TAT_DIRECTION_RANGED, list(TAT_DIRECTION_RANGED = 1), 1), \
	TRAIT_FIREARMS_MARKSMAN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_RANGED, list(TAT_DIRECTION_RANGED = 3), 3), \
	TRAIT_EXPLOSIVE_SUPPLY = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 2), 2), \
	TAT_TRAIT_SADDLEBORN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 1), 1), \
	TAT_TRAIT_MASTER_OF_WANDERING = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 3), 3), \
	TRAIT_GRAVEROBBER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 2), 2), \
	TRAIT_NOSTINK = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 1), 1), \
	TRAIT_SELF_SUSTENANCE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 3), 3), \
	TAT_TRAIT_PARTY_LEADER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 2), 2), \
	TRAIT_INTELLECTUAL = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TRAIT_JACKOFALLTRADES = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TRAIT_EMPATH = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TRAIT_CICERONE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TRAIT_SEEPRICES = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TRAIT_DECEIVING_MEEKNESS = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TRAIT_PURITAN_ADVENTURER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 1), 1), \
	TAT_TRAIT_FIREARMS_SUPPLIER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_RANGED, list(TAT_DIRECTION_RANGED = 3), 3), \
	TAT_TRAIT_BRONZE_SUPPLIER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 1), 1), \
	TAT_TRAIT_STEEL_SUPPLIER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 2), 2), \
	TAT_TRAIT_LEATHER_SUPPLIER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 1), 1), \
	TAT_TRAIT_MAIL_SUPPLIER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 1), 1), \
	TAT_TRAIT_PLATE_SUPPLIER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 1), 1), \
	TAT_TRAIT_SILVER_SUPPLIER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_COMBAT, list(TAT_DIRECTION_COMBAT = 4), 4), \
	TAT_TRAIT_TRADER_LICENSE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 1), 1), \
	TAT_TRAIT_ARTIFACTS_SUPPLIER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 3), 3), \
	TAT_TRAIT_LOOTRAT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 1), 1), \
	TAT_TRAIT_LOOTRAT_2 = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SURVIVAL, list(TAT_DIRECTION_SURVIVAL = 2), 2), \
	TAT_TRAIT_MASTER_OF_CRAFTING = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_STRAYING_SOUL = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_HANDICRAFT_APPRENTICE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_STRAYING_SOUL_APPRENTICE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TRAIT_KEENEARS = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_CONTRACTOR_ENTITY = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TAT_TRAIT_FREE_SOUL_RENAME = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_NASTY_EATER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_GOODLOVER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TRAIT_TECHNOPHOBE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_BAD_MOOD = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_PACIFISM = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_CRITICAL_WEAKNESS = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_NUDIST = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_SHIRTLESS = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_INHUMEN_ANATOMY = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 1), 1), \
	TRAIT_DISFIGURED = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 1), 1), \
	TRAIT_SPELLCOCKBLOCK = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_NOSLEEP = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_NORUN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_NUDE_SLEEPER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_EASYDISMEMBER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_PERMAMUTE = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TRAIT_NODEF = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TAT_TRAIT_ACCURSED = TAT_DIRECTION_ENTRY(TAT_DIRECTION_ORDINARY, list(TAT_DIRECTION_ORDINARY = 0), 0), \
	TAT_TRAIT_TRAINEE_SMITH = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_ARMORER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_WEAPONSMITH = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_WOODSMAN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_SURVIVALIST = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_POACHER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_SKULKER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_VAGABOND = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_RIDER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_MARINER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_CLOTHIER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_HOMESTEADER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_ARTISAN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_CHIRURGEON = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_TRAINEE_TROUBADOUR = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_HUNTER_BEATER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_HUNTER_SHOOTER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TAT_TRAIT_SKILLED_FORGEHAND = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_SKILLED_ARMORER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_SKILLED_WEAPONSMITH = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_SKILLED_ARTISAN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_SKILLED_WOODSMAN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_MASTER_CRAFTSMAN = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_SKILLED_MASON = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_SKILLED_COOK = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_SKILLED_ALCHEMIST = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_SKILLED_PHYSICKER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_SKILLED_SURVIVALIST = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TAT_TRAIT_SKILLED_CLOTHIER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TRAIT_SEEDKNOW = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TRAIT_CAUTIOUS_FISHER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TRAIT_EXPERT_HUNTER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 1), 1), \
	TRAIT_SQUIRE_REPAIR = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2), \
	TRAIT_ALCHEMY_EXPERT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 3), 3), \
	TRAIT_MEDICINE_EXPERT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 3), 3), \
	TRAIT_SEWING_EXPERT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 3), 3), \
	TRAIT_SURVIVAL_EXPERT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 3), 3), \
	TRAIT_MASTERFUL_HUNTER = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 3), 3), \
	TRAIT_ENCHANTING_EXPERT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 3), 3), \
	TRAIT_SMITHING_EXPERT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 4), 4), \
	TRAIT_HOMESTEAD_EXPERT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 4), 4), \
	TAT_TRAIT_POLYGLOT = TAT_DIRECTION_ENTRY(TAT_DIRECTION_SKILLS, list(TAT_DIRECTION_SKILLS = 2), 2) \
)

// The single-Starter build deliberately has no role/foundation gates on top of
// this table (see get_trait_rule() in tat_directions.dm) — every trait is
// purchasable regardless of archetype. Direction categorization and point
// costs above still apply.
GLOBAL_LIST_INIT(tat_direction_names, TAT_DIRECTION_NAMES)
GLOBAL_LIST_INIT(tat_foundation_names, TAT_FOUNDATION_NAMES)
GLOBAL_LIST_INIT(tat_foundation_role_choices, TAT_FOUNDATION_ROLE_CHOICES)
GLOBAL_LIST_INIT(tat_role_choice_names, TAT_ROLE_CHOICE_NAMES)
GLOBAL_LIST_INIT(tat_direction_trait_rules, TAT_DIRECTION_TRAIT_RULES)


