#define CRIPPLE_DAMAGE_PENALTY_MINOR 0.2
#define CRIPPLE_DAMAGE_PENALTY_MAJOR 0.4

#define CRIPPLE_ATTACK_DELAY_MINOR 1.05
#define CRIPPLE_ATTACK_DELAY_MAJOR 1.2

#define CRIPPLE_MOVE_PENALTY_MINOR (0.15 SECONDS)
#define CRIPPLE_MOVE_PENALTY_MAJOR (0.4 SECONDS)

#define CRIPPLE_SLOWDOWN 1
